<div class="space-y-2">
    <label for="specifically" class="block text-sm font-medium text-gray-700">Specific Use</label>
    <select id="specifically" name="specifically" class="w-full p-2 border border-gray-300 rounded-md text-sm">
        <option value="">Select Specific Use</option>
        <option value="AGRICULTURAL">AGRICULTURAL</option>
        <option value="AGRICULTURAL MILL">AGRICULTURAL MILL</option>
        <option value="AGRICULTURE">AGRICULTURE</option>
        <option value="AGRICULTURE (MIX FARMING)">AGRICULTURE (MIX FARMING)</option>
        <option value="AGRO ALLIED">AGRO ALLIED</option>
        <option value="ALUMINIUM WORKS">ALUMINIUM WORKS</option>
        <option value="BAKERY">BAKERY</option>
        <option value="BANK">BANK</option>
        <option value="BANK HALL">BANK HALL</option>
        <option value="BANKING HALL">BANKING HALL</option>
        <option value="BLOCK INDUSTRY">BLOCK INDUSTRY</option>
        <option value="BLOCK MAKING">BLOCK MAKING</option>
        <option value="BLOCK MAKING / INTERLOCK">BLOCK MAKING / INTERLOCK</option>
        <option value="BOOK SHOP">BOOK SHOP</option>
        <option value="BOTTLE WATER">BOTTLE WATER</option>
        <option value="BOTTLED WATER PRODUCT">BOTTLED WATER PRODUCT</option>
        <option value="BREAD BAKERY">BREAD BAKERY</option>
        <option value="BUILDING CONSTRUCTION">BUILDING CONSTRUCTION</option>
        <option value="CHILDREN PLAY GROUND">CHILDREN PLAY GROUND</option>
        <option value="CLAY BRICK FACTORY">CLAY BRICK FACTORY</option>
        <option value="CLINIC">CLINIC</option>
        <option value="COMMERCE">COMMERCE</option>
        <option value="COMMERCIAL">COMMERCIAL</option>
        <option value="COMMERCIAL (SHOPPING MALL)">COMMERCIAL (SHOPPING MALL)</option>
        <option value="COMMERCIAL AND RESIDENTIAL">COMMERCIAL AND RESIDENTIAL</option>
        <option value="COMMERCIAL SHOPS">COMMERCIAL SHOPS</option>
        <option value="CULTIVATION">CULTIVATION</option>
        <option value="CULTIVATION FARMING">CULTIVATION FARMING</option>
        <option value="CULTURAL CENTRE">CULTURAL CENTRE</option>
        <option value="EDUCATIONAL INSTITUTE">EDUCATIONAL INSTITUTE</option>
        <option value="EDUCATIONAL INSTITUTION">EDUCATIONAL INSTITUTION</option>
        <option value="EVENT CENTER">EVENT CENTER</option>
        <option value="EVENT CENTRE">EVENT CENTRE</option>
        <option value="EVENT HALL SHOPS & OFFICES">EVENT HALL SHOPS & OFFICES</option>
        <option value="FACTORY HALLS, WAREHOUSES AND OFFICES">FACTORY HALLS, WAREHOUSES AND OFFICES</option>
        <option value="FARMING">FARMING</option>
        <option value="FILLING STATION">FILLING STATION</option>
        <option value="FISH FARMING">FISH FARMING</option>
        <option value="FISHERY">FISHERY</option>
        <option value="FOAM PRODUCTS">FOAM PRODUCTS</option>
        <option value="FOOD PROCESSING">FOOD PROCESSING</option>
        <option value="FRIDAY MOSQUE">FRIDAY MOSQUE</option>
        <option value="GARAGE">GARAGE</option>
        <option value="GARAGE AND SHOPPING PLAZA">GARAGE AND SHOPPING PLAZA</option>
        <option value="GARAGE PARKS">GARAGE PARKS</option>
        <option value="GARAGE, SHOPS AND OFFICES">GARAGE, SHOPS AND OFFICES</option>
        <option value="GAS PLANT">GAS PLANT</option>
        <option value="GUEST INN">GUEST INN</option>
        <option value="GWALE">GWALE</option>
        <option value="HOSPITAL">HOSPITAL</option>
        <option value="HOTEL">HOTEL</option>
        <option value="HOTEL AND RESORT">HOTEL AND RESORT</option>
        <option value="HOTEL SERVICE">HOTEL SERVICE</option>
        <option value="HOUSING ESTATE">HOUSING ESTATE</option>
        <option value="HUSBANDRY">HUSBANDRY</option>
        <option value="INDUSTRY">INDUSTRY</option>
        <option value="INDUSTRY (TANNERY)">INDUSTRY (TANNERY)</option>
        <option value="INDUSTRY MOTOR GARAGE AND OFFICES">INDUSTRY MOTOR GARAGE AND OFFICES</option>
        <option value="ISLAMIYYA SCHOOL">ISLAMIYYA SCHOOL</option>
        <option value="LEATHER INDUSTRY">LEATHER INDUSTRY</option>
        <option value="LIVESTOCK/FISH FARMING">LIVESTOCK/FISH FARMING</option>
        <option value="LPG">LPG</option>
        <option value="LPG PLANT">LPG PLANT</option>
        <option value="MECHANIC GARAGE">MECHANIC GARAGE</option>
        <option value="MECHANIC YARD">MECHANIC YARD</option>
        <option value="MECHANICAL SERVICES">MECHANICAL SERVICES</option>
        <option value="MEDICAL HOSPITAL">MEDICAL HOSPITAL</option>
        <option value="METAL & PLASTIC">METAL & PLASTIC</option>
        <option value="METAL WORKS">METAL WORKS</option>
        <option value="MIIXED FARMING">MIIXED FARMING</option>
        <option value="MIX FARMING">MIX FARMING</option>
        <option value="MIXED AGRICULTURE">MIXED AGRICULTURE</option>
        <option value="MIXED FARMING">MIXED FARMING</option>
        <option value="MOSQUE">MOSQUE</option>
        <option value="MOTOR GARAGE">MOTOR GARAGE</option>
        <option value="MOTOR GARAGE AND WAREHOUSE">MOTOR GARAGE AND WAREHOUSE</option>
        <option value="NURSERY/PRIMARY SCHOOL">NURSERY/PRIMARY SCHOOL</option>
        <option value="OFFICE">OFFICE</option>
        <option value="OFFICE & STORE">OFFICE & STORE</option>
        <option value="OFFICE &SHOPS">OFFICE &SHOPS</option>
        <option value="OFFICE / WAREHOUSE">OFFICE / WAREHOUSE</option>
        <option value="OFFICE AND EVENT CENTER">OFFICE AND EVENT CENTER</option>
        <option value="OFFICE AND MOTOR GARAGE">OFFICE AND MOTOR GARAGE</option>
        <option value="OFFICE AND WAREHOUSE">OFFICE AND WAREHOUSE</option>
        <option value="OFFICE COMPLEX">OFFICE COMPLEX</option>
        <option value="OFFICE HALL">OFFICE HALL</option>
        <option value="OFFICE SHOPPING COMPLEX">OFFICE SHOPPING COMPLEX</option>
        <option value="OFFICE/WAREHOUSE">OFFICE/WAREHOUSE</option>
        <option value="OFFICES">OFFICES</option>
        <option value="OFFICES & SHOPS">OFFICES & SHOPS</option>
        <option value="OFFICES AND GARAGE">OFFICES AND GARAGE</option>
        <option value="OFFICES AND SALES">OFFICES AND SALES</option>
        <option value="OFFICES FLATS AND GARAGE">OFFICES FLATS AND GARAGE</option>
        <option value="OFFICES, STORES AND PETROL FILLING STATION">OFFICES, STORES AND PETROL FILLING STATION</option>
        <option value="OIL MILL">OIL MILL</option>
        <option value="OIL MILLS">OIL MILLS</option>
        <option value="ORCHARD">ORCHARD</option>
        <option value="PARK AND GARDEN">PARK AND GARDEN</option>
        <option value="PETROL FILLING STATION">PETROL FILLING STATION</option>
        <option value="PETROL FILLING STATION">PETROL FILLING STATION</option>
        <option value="PETROL STATION">PETROL STATION</option>
        <option value="PHARMACEUTICAL">PHARMACEUTICAL</option>
        <option value="PHARMACEUTICAL STORE">PHARMACEUTICAL STORE</option>
        <option value="PLANTATION">PLANTATION</option>
        <option value="PLASTIC AND FLEXIBLE PACKAGING PRODUCTS">PLASTIC AND FLEXIBLE PACKAGING PRODUCTS</option>
        <option value="PLASTIC AND SACKS">PLASTIC AND SACKS</option>
        <option value="PLASTIC PROCESSING PLAN">PLASTIC PROCESSING PLAN</option>
        <option value="PLAZA">PLAZA</option>
        <option value="POULTRY">POULTRY</option>
        <option value="POULTRY FARM">POULTRY FARM</option>
        <option value="POULTRY FARMING">POULTRY FARMING</option>
        <option value="POULTRY FARMING">POULTRY FARMING</option>
        <option value="PRIMARY SCHOOL">PRIMARY SCHOOL</option>
        <option value="PRIVATE SCHOOL">PRIVATE SCHOOL</option>
        <option value="PRIVATE UNIVERSITY">PRIVATE UNIVERSITY</option>
        <option value="PURE WATER">PURE WATER</option>
        <option value="PURE WATER FACTORY">PURE WATER FACTORY</option>
        <option value="QUARRY SITE">QUARRY SITE</option>
        <option value="RES">RES</option>
        <option value="RESIDENCE">RESIDENCE</option>
        <option value="RESIDENCE">RESIDENCE</option>
        <option value="'RESIDENCE">'RESIDENCE</option>
        <option value="RESIDENTCE">RESIDENTCE</option>
        <option value="RESIDENTIAL">RESIDENTIAL</option>
        <option value="RESIDENTIAL AND COMMERCIAL">RESIDENTIAL AND COMMERCIAL</option>
        <option value="RESIDENTIAL/COMMERCIAL">RESIDENTIAL/COMMERCIAL</option>
        <option value="RESIDENTIAL/COMMERCIAL LAYOUT">RESIDENTIAL/COMMERCIAL LAYOUT</option>
        <option value="RESIDENTIIAL">RESIDENTIIAL</option>
        <option value="RESIDNCE">RESIDNCE</option>
        <option value="RESTAURANT">RESTAURANT</option>
        <option value="RESTURANT">RESTURANT</option>
        <option value="RICE AND FEED MILL">RICE AND FEED MILL</option>
        <option value="RICE AND OIL MILLS">RICE AND OIL MILLS</option>
        <option value="RICE MILL">RICE MILL</option>
        <option value="RICE MILLING">RICE MILLING</option>
        <option value="RICE MILLS">RICE MILLS</option>
        <option value="RICE PROCESSING MILLS">RICE PROCESSING MILLS</option>
        <option value="SACHET WATER AND DAIRY PRODUCTS">SACHET WATER AND DAIRY PRODUCTS</option>
        <option value="SACK MANUFACTURING & PRODUCTION">SACK MANUFACTURING & PRODUCTION</option>
        <option value="SAMLL SCALE IRON FABRICATION">SAMLL SCALE IRON FABRICATION</option>
        <option value="SANDO">SANDO</option>
        <option value="SCHOOL">SCHOOL</option>
        <option value="SEASONAL FARMING">SEASONAL FARMING</option>
        <option value="SEED PLANTATION">SEED PLANTATION</option>
        <option value="SHOP">SHOP</option>
        <option value="SHOP & OFFICES">SHOP & OFFICES</option>
        <option value="SHOP AND OFFICE">SHOP AND OFFICE</option>
        <option value="SHOPPING COMPLEX">SHOPPING COMPLEX</option>
        <option value="SHOPPING COMPLEX AND OFFICES">SHOPPING COMPLEX AND OFFICES</option>
        <option value="SHOPPING COMPLEX/OFFICES">SHOPPING COMPLEX/OFFICES</option>
        <option value="SHOPPING MALL">SHOPPING MALL</option>
        <option value="SHOPPING MALL AND OFFICES">SHOPPING MALL AND OFFICES</option>
        <option value="SHOPPING MALL/COMPLEX">SHOPPING MALL/COMPLEX</option>
        <option value="SHOPPING PLAZA">SHOPPING PLAZA</option>
        <option value="SHOPS">SHOPS</option>
        <option value="SHOPS & OFFICES">SHOPS & OFFICES</option>
        <option value="SHOPS & STORES">SHOPS & STORES</option>
        <option value="SHOPS AND GARAGE">SHOPS AND GARAGE</option>
        <option value="SHOPS AND OFFICES">SHOPS AND OFFICES</option>
        <option value="SHOPS AND OFFICES BLOCK">SHOPS AND OFFICES BLOCK</option>
        <option value="SHOPS AND SCHOOL">SHOPS AND SCHOOL</option>
        <option value="SHOPS AND STORE">SHOPS AND STORE</option>
        <option value="SHOPS OFFICES">SHOPS OFFICES</option>
        <option value="SHOPS, OFFICE, AND STORE">SHOPS, OFFICE, AND STORE</option>
        <option value="SHOWROOM AND OFFICE">SHOWROOM AND OFFICE</option>
        <option value="SMALL SCALE">SMALL SCALE</option>
        <option value="SMALL SCALE & ESTATE">SMALL SCALE & ESTATE</option>
        <option value="SMALL SCALE INDUSTRIAL">SMALL SCALE INDUSTRIAL</option>
        <option value="STORE">STORE</option>
        <option value="STORE AND OFFICES">STORE AND OFFICES</option>
        <option value="STORE AND WAREHOUSE">STORE AND WAREHOUSE</option>
        <option value="STORE, WAREHOUSE & OFFICIES">STORE, WAREHOUSE & OFFICIES</option>
        <option value="STORES AND OFFICES">STORES AND OFFICES</option>
        <option value="STORES AND WAREHOUSE">STORES AND WAREHOUSE</option>
        <option value="SUPER MARKET">SUPER MARKET</option>
        <option value="SUPERMARKET">SUPERMARKET</option>
        <option value="SUPERMARKET & DEPART. STORES">SUPERMARKET & DEPART. STORES</option>
        <option value="TANNARY">TANNARY</option>
        <option value="TRADE & RESIDENCE">TRADE & RESIDENCE</option>
        <option value="TRAILER PARK / GARAGE">TRAILER PARK / GARAGE</option>
        <option value="TRAINING CENTRE">TRAINING CENTRE</option>
        <option value="UNIVERSITY">UNIVERSITY</option>
        <option value="WARE HOUSE">WARE HOUSE</option>
        <option value="WARE HOUSE & OFFICES">WARE HOUSE & OFFICES</option>
        <option value="WARE HOUSE AND OFFICES">WARE HOUSE AND OFFICES</option>
        <option value="WARE HOUSE AND SHOPS">WARE HOUSE AND SHOPS</option>
        <option value="WAREHOUSE">WAREHOUSE</option>
        <option value="WAREHOUSE & SHOW ROOM">WAREHOUSE & SHOW ROOM</option>
        <option value="WARE-HOUSE AND OFFICE">WARE-HOUSE AND OFFICE</option>
        <option value="WAREHOUSE AND OFFICES">WAREHOUSE AND OFFICES</option>
        <option value="WAREHOUSE AND STORE">WAREHOUSE AND STORE</option>
        <option value="WAREHOUSE/ GARAGE">WAREHOUSE/ GARAGE</option>
        <option value="WORK SHOP">WORK SHOP</option>
        <option value="WORKSHOP AND OFFICES">WORKSHOP AND OFFICES</option>
    </select>
</div>
