<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;

class EdmsSchemaChecker
{
    protected $conn = 'sqlsrv';

    public function generateSql(): string
    {
        $sections = [];
        $sections[] = '-- EDMS Schema Auto-Check Script (T-SQL for SQL Server)';
        $sections[] = '-- Generated by EdmsSchemaChecker. Review and run manually.';
        $sections[] = 'SET NOCOUNT ON;';

        // file_indexings required columns and FK
        $sections[] = $this->ensureFileIndexings();

        // file_trackings link to file_indexings
        $sections[] = $this->ensureFileTrackings();

        // pagetypings table and required columns
        $sections[] = $this->ensurePageTypings();

        // property_records table
        $sections[] = $this->ensurePropertyRecords();

        // batches table
        $sections[] = $this->ensureBatches();

        // barcodes table
        $sections[] = $this->ensureBarcodes();

        return implode("\n\n", array_filter($sections));
    }

    protected function ensureFileIndexings(): string
    {
        $sql = [];
        $sql[] = '-- Ensure file_indexings has is_updated, batch_id, has_qc_issues and FK to batches';
        $sql[] = "IF COL_LENGTH('file_indexings','is_updated') IS NULL\nBEGIN\n    ALTER TABLE file_indexings ADD is_updated BIT NOT NULL CONSTRAINT DF_file_indexings_is_updated DEFAULT(0);\nEND";
        $sql[] = "IF COL_LENGTH('file_indexings','batch_id') IS NULL\nBEGIN\n    ALTER TABLE file_indexings ADD batch_id BIGINT NULL;\nEND";
        $sql[] = "IF COL_LENGTH('file_indexings','has_qc_issues') IS NULL\nBEGIN\n    ALTER TABLE file_indexings ADD has_qc_issues BIT NOT NULL CONSTRAINT DF_file_indexings_has_qc_issues DEFAULT(0);\nEND";
        // FK to batches
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_file_indexings_batches')\nBEGIN\n    IF COL_LENGTH('file_indexings','batch_id') IS NOT NULL AND EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = 'batches')\n    BEGIN\n        ALTER TABLE file_indexings\n        ADD CONSTRAINT FK_file_indexings_batches FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE SET NULL;\n    END\nEND";
        return implode("\n", $sql);
    }

    protected function ensureFileTrackings(): string
    {
        $sql = [];
        $sql[] = '-- Ensure file_trackings has file_indexing_id and FK to file_indexings';
        $sql[] = "IF COL_LENGTH('file_trackings','file_indexing_id') IS NULL\nBEGIN\n    ALTER TABLE file_trackings ADD file_indexing_id BIGINT NULL;\nEND";
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_file_trackings_file_indexings')\nBEGIN\n    IF COL_LENGTH('file_trackings','file_indexing_id') IS NOT NULL AND EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = 'file_indexings')\n    BEGIN\n        ALTER TABLE file_trackings\n        ADD CONSTRAINT FK_file_trackings_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;\n    END\nEND";
        return implode("\n", $sql);
    }

    protected function ensurePageTypings(): string
    {
        $sql = [];
        $sql[] = '-- Ensure pagetypings table/columns exist';
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'pagetypings')\nBEGIN\n    CREATE TABLE pagetypings (\n        id BIGINT IDENTITY(1,1) PRIMARY KEY,\n        file_indexing_id BIGINT NOT NULL,\n        scanning_id BIGINT NULL,\n        page_number INT NOT NULL,\n        page_type NVARCHAR(100) NOT NULL,\n        page_subtype NVARCHAR(100) NULL,\n        serial_number INT NOT NULL,\n        page_code NVARCHAR(100) NULL,\n        file_path NVARCHAR(255) NOT NULL,\n        typed_by BIGINT NULL,\n        source NVARCHAR(50) NOT NULL CONSTRAINT DF_pagetypings_source DEFAULT('initial'),\n        qc_overridden BIT NOT NULL CONSTRAINT DF_pagetypings_qc_overridden DEFAULT(0),\n        qc_override_note NVARCHAR(1000) NULL,\n        created_at DATETIME2 NOT NULL CONSTRAINT DF_pagetypings_created_at DEFAULT (GETDATE()),\n        updated_at DATETIME2 NOT NULL CONSTRAINT DF_pagetypings_updated_at DEFAULT (GETDATE()),\n        deleted_at DATETIME2 NULL\n    );\n    CREATE INDEX IX_pagetypings_file_idx ON pagetypings(file_indexing_id);\n    CREATE INDEX IX_pagetypings_scanning_id ON pagetypings(scanning_id);\n    ALTER TABLE pagetypings ADD CONSTRAINT FK_pagetypings_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;\nEND";
        // Add missing columns if table exists
        $addCols = [
            "source NVARCHAR(50) NOT NULL CONSTRAINT DF_pagetypings_source DEFAULT('initial')",
            "qc_overridden BIT NOT NULL CONSTRAINT DF_pagetypings_qc_overridden DEFAULT(0)",
            "qc_override_note NVARCHAR(1000) NULL",
            "deleted_at DATETIME2 NULL",
            "serial_suffix NVARCHAR(5) NULL",
            "is_bcfc_page BIT NOT NULL CONSTRAINT DF_pagetypings_is_bcfc_page DEFAULT(0)",
            "bcfc_sequence NVARCHAR(5) NULL",
            "bcfc_id NVARCHAR(50) NULL"
        ];
        foreach ($addCols as $def) {
            [$col] = explode(' ', $def, 2);
            $sql[] = "IF COL_LENGTH('pagetypings','{$col}') IS NULL\nBEGIN\n    ALTER TABLE pagetypings ADD {$def};\nEND";
        }
        return implode("\n", $sql);
    }

    protected function ensurePropertyRecords(): string
    {
        $sql = [];
        $sql[] = '-- Ensure property_records table/columns exist';
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records')\nBEGIN\n    CREATE TABLE property_records (\n        id BIGINT IDENTITY(1,1) PRIMARY KEY,\n        file_indexing_id BIGINT NOT NULL,\n        instrument_type NVARCHAR(100) NOT NULL,\n        reg_no NVARCHAR(100) NULL,\n        reg_date DATE NULL,\n        grantor NVARCHAR(255) NULL,\n        grantee NVARCHAR(255) NULL,\n        extras NVARCHAR(MAX) NULL,\n        created_by BIGINT NULL,\n        created_at DATETIME2 NOT NULL CONSTRAINT DF_property_records_created_at DEFAULT (GETDATE()),\n        updated_at DATETIME2 NOT NULL CONSTRAINT DF_property_records_updated_at DEFAULT (GETDATE())\n    );\n    CREATE INDEX IX_property_records_file_idx ON property_records(file_indexing_id);\n    ALTER TABLE property_records ADD CONSTRAINT FK_property_records_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;\nEND";
        // Add missing columns common in PRA workflow
        $columns = [
            'instrument_type NVARCHAR(100) NOT NULL',
            'reg_no NVARCHAR(100) NULL',
            'reg_date DATE NULL',
            'grantor NVARCHAR(255) NULL',
            'grantee NVARCHAR(255) NULL',
            'extras NVARCHAR(MAX) NULL',
        ];
        foreach ($columns as $def) {
            [$col] = explode(' ', $def, 2);
            $sql[] = "IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','{$col}') IS NULL\nBEGIN\n    ALTER TABLE property_records ADD {$def};\nEND";
        }
        return implode("\n", $sql);
    }

    protected function ensureBatches(): string
    {
        $sql = [];
        $sql[] = '-- Ensure batches table exists';
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'batches')\nBEGIN\n    CREATE TABLE batches (\n        id BIGINT IDENTITY(1,1) PRIMARY KEY,\n        name NVARCHAR(150) NOT NULL,\n        size INT NOT NULL CONSTRAINT DF_batches_size DEFAULT(0),\n        created_by BIGINT NULL,\n        notes NVARCHAR(1000) NULL,\n        created_at DATETIME2 NOT NULL CONSTRAINT DF_batches_created_at DEFAULT (GETDATE()),\n        updated_at DATETIME2 NOT NULL CONSTRAINT DF_batches_updated_at DEFAULT (GETDATE())\n    );\nEND";
        return implode("\n", $sql);
    }

    protected function ensureBarcodes(): string
    {
        $sql = [];
        $sql[] = '-- Ensure barcodes table exists';
        $sql[] = "IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'barcodes')\nBEGIN\n    CREATE TABLE barcodes (\n        id BIGINT IDENTITY(1,1) PRIMARY KEY,\n        file_indexing_id BIGINT NOT NULL,\n        barcode_value NVARCHAR(150) NOT NULL,\n        qr_payload NVARCHAR(MAX) NULL,\n        printed_at DATETIME2 NULL,\n        created_at DATETIME2 NOT NULL CONSTRAINT DF_barcodes_created_at DEFAULT (GETDATE()),\n        updated_at DATETIME2 NOT NULL CONSTRAINT DF_barcodes_updated_at DEFAULT (GETDATE())\n    );\n    CREATE UNIQUE INDEX UX_barcodes_barcode_value ON barcodes(barcode_value);\n    CREATE INDEX IX_barcodes_file_idx ON barcodes(file_indexing_id);\n    ALTER TABLE barcodes ADD CONSTRAINT FK_barcodes_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;\nEND";
        return implode("\n", $sql);
    }
}
