-- indexing_duplicates
-- Column-for-column clone of file_indexings (all cloned columns nullable),
-- plus the move metadata. [id] is this table's own identity; the original
-- file_indexings.id is kept in [file_indexing_id].
-- Generated from the live table on 2026-07-30 10:30:35.

CREATE TABLE [dbo].[indexing_duplicates] (
    [id]                              BIGINT IDENTITY(1,1) NOT NULL,
    [file_indexing_id]                BIGINT NULL,
    [main_application_id]             INT NULL,
    [subapplication_id]               INT NULL,
    [recertification_application_id]  INT NULL,
    [st_fillno]                       NVARCHAR(100) NULL,
    [file_number_id]                  INT NULL,
    [file_number]                     NVARCHAR(100) NULL,
    [file_title]                      NVARCHAR(MAX) NULL,
    [land_use_type]                   NVARCHAR(100) NULL,
    [plot_number]                     NVARCHAR(100) NULL,
    [district]                        NVARCHAR(100) NULL,
    [lga]                             NVARCHAR(100) NULL,
    [has_cofo]                        BIT NULL,
    [is_merged]                       BIT NULL,
    [has_transaction]                 BIT NULL,
    [is_problematic]                  BIT NULL,
    [is_co_owned_plot]                BIT NULL,
    [created_at]                      DATETIME NULL,
    [updated_at]                      DATETIME NULL,
    [created_by]                      NVARCHAR(50) NULL,
    [updated_by]                      NVARCHAR(50) NULL,
    [serial_no]                       NVARCHAR(50) NULL,
    [batch_no]                        INT NULL,
    [shelf_location]                  NVARCHAR(255) NULL,
    [is_updated]                      BIT NULL,
    [batch_id]                        INT NULL,
    [has_qc_issues]                   BIT NULL,
    [workflow_status]                 NVARCHAR(50) NULL,
    [archived_at]                     DATETIME NULL,
    [shelf_label_id]                  INT NULL,
    [assigned_by]                     INT NULL,
    [assigned_at]                     DATETIME NULL,
    [reserved_by]                     INT NULL,
    [reserved_at]                     DATETIME NULL,
    [status]                          NVARCHAR(50) NULL,
    [registry]                        NVARCHAR(100) NULL,
    [location]                        NVARCHAR(255) NULL,
    [plot_size]                       NVARCHAR(50) NULL,
    [tp_no]                           NVARCHAR(100) NULL,
    [lpkn_no]                         NVARCHAR(100) NULL,
    [tracking_id]                     NVARCHAR(100) NULL,
    [batch_generated]                 BIT NULL,
    [last_batch_id]                   NVARCHAR(50) NULL,
    [batch_generated_at]              DATETIME NULL,
    [batch_generated_by]              INT NULL,
    [is_deleted]                      BIT NULL,
    [deleted_at]                      DATETIME NULL,
    [related_fileno]                  NVARCHAR(MAX) NULL,
    [sys_batch_no]                    NVARCHAR(MAX) NULL,
    [group]                           NVARCHAR(MAX) NULL,
    [date_migrated]                   NVARCHAR(MAX) NULL,
    [source]                          NVARCHAR(MAX) NULL,
    [migrated_by]                     NVARCHAR(50) NULL,
    [date_created]                    NVARCHAR(50) NULL,
    [prop_id]                         NVARCHAR(100) NULL,
    [test_control]                    NVARCHAR(50) NULL,
    [registry_batch_no]               NVARCHAR(50) NULL,
    [group_no]                        NVARCHAR(50) NULL,
    [source_file_id]                  NVARCHAR(50) NULL,
    [awaiting_file_no]                NVARCHAR(50) NULL,
    [st_batch_no]                     NVARCHAR(50) NULL,
    [physical_registry]               NVARCHAR(50) NULL,
    [captured_by]                     NVARCHAR(50) NULL,
    [file_type]                       NVARCHAR(20) NULL,
    [dob]                             DATE NULL,
    [nin]                             NVARCHAR(13) NULL,
    [tin]                             NVARCHAR(50) NULL,
    [rc_no]                           NVARCHAR(50) NULL,
    [country_code]                    NVARCHAR(10) NULL,
    [phone]                           NVARCHAR(20) NULL,
    [residence_address]               NVARCHAR(500) NULL,
    [general_registry]                NVARCHAR(255) NULL,
    [dciv_reason]                     NVARCHAR(MAX) NULL,
    [complainant]                     NVARCHAR(MAX) NULL,
    [original_holder]                 NVARCHAR(MAX) NULL,
    [current_holder]                  NVARCHAR(MAX) NULL,
    [holders_backfilled]              BIT NULL,
    [indexing_type]                   NVARCHAR(50) NULL,
    [street_name]                     NVARCHAR(50) NULL,
    [has_rofo]                        NCHAR(10) NULL,
    [is_duplicate]                    NVARCHAR(50) NULL,
    [has_temp_file]                   TINYINT NULL,
    [temp_file_no]                    NVARCHAR(100) NULL,
    [kangis_fileno_placeholder]       NVARCHAR(100) NULL,
    [kangis_fileno_resolved]          NVARCHAR(120) NULL,
    [is_corresponding_file]           BIT NULL,
    [corresponding_fileno]            NVARCHAR(50) NULL,
    [kangis_file_type]                VARCHAR(20) NULL,
    [mls_file_no]                     VARCHAR(100) NULL,
    [kangis_file_no]                  VARCHAR(100) NULL,
    [new_kangis_file_no]              VARCHAR(100) NULL,
    [sub_prefix]                      VARCHAR(30) NULL,
    [suffix]                          VARCHAR(30) NULL,
    [parent_prop_id]                  NVARCHAR(255) NULL,
    [digit_rank]                      TINYINT NULL,
    [title_status]                    TINYINT NULL,
    [title_status_type]               VARCHAR(100) NULL,
    [title_status_remark]             TEXT NULL,
    [st_application_type]             NVARCHAR(50) NULL,
    [tracking_status]                 NVARCHAR(50) NULL,
    [current_location]                NVARCHAR(255) NULL,
    [file_tracker_id]                 BIGINT NULL,
    [location_status_manual]          DATETIME NULL,
    [latitude]                        NVARCHAR(MAX) NULL,
    [longitude]                       NVARCHAR(MAX) NULL,
    [dciv_status]                     NVARCHAR(MAX) NULL,
    [dciv_fileno]                     NVARCHAR(MAX) NULL,
    [bill_total_amount]               DECIMAL(18,2) NULL,
    [bill_from_year]                  INT NULL,
    [bill_to_year]                    INT NULL,
    [bill_receipt_no]                 NVARCHAR(255) NULL,
    [bill_receipt_date]               DATE NULL,
    [ground_rent_amount]              DECIMAL(18,2) NULL,
    [ground_rent_from_year]           INT NULL,
    [ground_rent_to_year]             INT NULL,
    [ground_rent_receipt_no]          NVARCHAR(255) NULL,
    [ground_rent_receipt_date]        DATE NULL,
    [file_classification]             NVARCHAR(1000) NULL,
    [file_classification_remarks]     NVARCHAR(MAX) NULL,
    [pp_lands_fileno]                 NVARCHAR(255) NULL,
    [pp_lands_matching]               INT NULL,
    [pp_lands_date_matched]           DATE NULL,
    [pp_lands_time_matched]           TIME(7) NULL,
    [comment]                         NVARCHAR(MAX) NULL,
    [has_occupancy_permit]            NVARCHAR(50) NULL,
    [gender]                          NVARCHAR(10) NULL,

    -- ---- move metadata (not part of file_indexings) ----
    [duplicate_of]                    NVARCHAR(100) NULL,
    [reason]                          NVARCHAR(500) NULL,
    [mls_file_no_retained]            BIT NOT NULL DEFAULT ((0)),
    [snapshot]                        NVARCHAR(MAX) NULL,
    [deleted_counts]                  NVARCHAR(MAX) NULL,
    [moved_by]                        NVARCHAR(150) NULL,
    [moved_by_id]                     BIGINT NULL,
    [moved_at]                        DATETIME NULL,
    [restored_at]                     DATETIME NULL,
    [restored_by]                     NVARCHAR(150) NULL,
    CONSTRAINT [PK_indexing_duplicates] PRIMARY KEY CLUSTERED ([id])
);
GO

CREATE INDEX [idx_indexing_duplicates_file_number] ON [dbo].[indexing_duplicates] ([file_number]);
CREATE INDEX [idx_indexing_duplicates_file_indexing_id] ON [dbo].[indexing_duplicates] ([file_indexing_id]);
CREATE INDEX [idx_indexing_duplicates_prop_id] ON [dbo].[indexing_duplicates] ([prop_id]);
CREATE INDEX [idx_indexing_duplicates_moved_at] ON [dbo].[indexing_duplicates] ([moved_at]);
GO
