@extends('layouts.app')

{{--
  OP → File Property ID Matching.

  Left: the confirmed FILE, which is the control record. Its Property ID is the target
  and never moves. Right: the Occupancy Permits, searched by serial number because that
  is what is printed on the permit the officer is holding. Tick the ones that belong to
  the file, add them to the batch (repeating for as many serials as the file needs),
  then press Batch Match and every permit in the batch is moved onto the file's
  Property ID.

  The shell is the one match_op.blade.php uses and for the same two reasons:
  admin.header loads Tailwind v3 (layouts/app only carries v2, which has no arbitrary
  values and none of the slate/violet palette used here), and the
  "flex-1 overflow-auto relative" wrapper is what app-layout.css sizes the content pane
  with — without it the page renders in a half-width column beside the sidebar.

  Everything below is drawn and driven by public/js/op-propid-match.js, which keys off
  the ids on #op-propid-match and reads its endpoints from that element's data
  attributes. No markup here is generated by the script except the three result lists.
--}}

@section('content')
<div class="flex-1 overflow-auto bg-slate-50/60 relative">
  @include('admin.header')

  <div id="op-propid-match"
       class="py-8 px-4 sm:px-6 lg:px-8 max-w-[1600px] mx-auto"
       data-file-url="{{ route('op-propid-match.file') }}"
       data-ops-url="{{ route('op-propid-match.ops') }}"
       data-batch-url="{{ route('op-propid-match.batch') }}"
       data-batches-url="{{ route('op-propid-match.batches') }}"
       data-undo-url="{{ route('op-propid-match.undo') }}"
       data-csrf="{{ csrf_token() }}">

    {{-- Page header --}}
    <div class="bg-white rounded-2xl shadow-sm border border-slate-200 px-6 py-5 mb-5">
      <div class="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 class="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <i data-lucide="link-2" class="h-6 w-6 text-violet-600"></i>
            Match OP Property ID
          </h1>
          {{-- What every batch from this page is recorded as. There is only one kind
               of match here, so it is stated rather than asked: the permits belong to
               the file exactly as it already stands, and nothing about ownership is
               being asserted. The server writes this value regardless of what the
               browser sends. --}}
          <div class="mt-2">
            <span class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border border-emerald-300 bg-emerald-50 text-emerald-900">
              <i data-lucide="shield-check" class="h-3.5 w-3.5"></i>
              {{ $matchModeLabel }}
            </span>
          </div>
          <p class="text-slate-500 text-sm mt-1 max-w-3xl">
            Occupancy Permits captured before their file was confirmed each carry a Property ID of their own,
            so the file's records read as separate properties. Select the confirmed file, select the permits that
            belong to it, and Batch Match moves them all onto the file's Property ID.
          </p>
        </div>
        <button type="button" id="opm-reset"
                class="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-700 bg-white hover:bg-slate-50 rounded-lg transition border border-slate-200 shadow-sm">
          <i data-lucide="rotate-ccw" class="h-4 w-4"></i> Start over
        </button>
      </div>
    </div>

    {{-- Banner: the one place every result and refusal is reported. --}}
    <div id="opm-banner" class="hidden mb-5"></div>

    <div class="grid grid-cols-1 xl:grid-cols-2 gap-5 items-start">

      {{-- ============================ LEFT: the file ============================ --}}
      <section class="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
        <header class="px-6 py-4 border-b border-slate-200 bg-gradient-to-r from-violet-50 to-white">
          <div class="flex items-center gap-3">
            <span class="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-600 text-white text-sm font-bold">1</span>
            <div>
              <h2 class="text-base font-semibold text-slate-900">Confirmed File — the control record</h2>
              <p class="text-xs text-slate-500">Its Property ID is the target. It never changes.</p>
            </div>
          </div>
        </header>

        <div class="p-6 space-y-4">
          {{-- The file is chosen through the shared Global File Number Selector — the
               same picker every other screen uses, with its MLS / KANGIS / New KANGIS
               tabs and its own search. This page deliberately has no file search of its
               own: a second one would go stale against the registries the shared picker
               already knows how to read. The display input is read-only and opens the
               picker on click, as it does on the other screens that use it. --}}
          <div>
            <label for="opm-file-display" class="block text-xs font-semibold text-slate-600 uppercase tracking-wide mb-1.5">
              File number
            </label>
            <div class="flex gap-2">
              <input type="text" id="opm-file-display" readonly
                     placeholder="Click to choose a file number"
                     class="flex-1 px-4 py-2.5 rounded-lg border border-slate-300 bg-slate-50 text-sm font-medium cursor-pointer focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition">
              <button type="button" id="opm-file-pick-btn"
                      class="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-white bg-violet-600 hover:bg-violet-700 rounded-lg transition shadow-sm whitespace-nowrap">
                <i data-lucide="folder-search" class="h-4 w-4"></i> Select File Number
              </button>
            </div>
            <p class="text-[11px] text-slate-400 mt-1.5">
              The file must be in MLS File Numbers or File Indexing. Its Property ID loads as the match target.
            </p>
          </div>

          {{-- The chosen file and its target Property ID. --}}
          <div id="opm-file-selected" class="hidden"></div>

          {{-- What is already on that Property ID. --}}
          <div id="opm-file-existing" class="hidden"></div>
        </div>
      </section>

      {{-- ============================ RIGHT: the OPs ============================ --}}
      <section class="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
        <header class="px-6 py-4 border-b border-slate-200 bg-gradient-to-r from-emerald-50 to-white">
          <div class="flex items-center justify-between gap-3">
            <div class="flex items-center gap-3">
              <span class="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-600 text-white text-sm font-bold">2</span>
              <div>
                <h2 class="text-base font-semibold text-slate-900">Occupancy Permits</h2>
                <p class="text-xs text-slate-500">Search by OP serial number, tick one or many, then Add to Batch. Repeat for each serial.</p>
              </div>
            </div>
            <button type="button" id="opm-advanced-toggle"
                    class="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-slate-600 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg transition">
              <i data-lucide="sliders-horizontal" class="h-3.5 w-3.5"></i>
              <span id="opm-advanced-label">Advanced search</span>
            </button>
          </div>
        </header>

        <div class="p-6 space-y-4">
          <div>
            <label for="opm-serial" class="block text-xs font-semibold text-slate-600 uppercase tracking-wide mb-1.5">
              OP serial number(s)
            </label>
            <div class="flex gap-2">
              <input type="text" id="opm-serial" autocomplete="off" spellcheck="false"
                     placeholder="e.g. 989 — or a list: 989, 990, 991"
                     class="flex-1 px-3 py-2.5 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500">
              <select id="opm-serial-mode"
                      class="px-2 py-2.5 text-xs border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 bg-white">
                <option value="exact">Exact</option>
                <option value="starts">Starts with</option>
                <option value="contains">Contains</option>
              </select>
            </div>
            <p class="text-[11px] text-slate-400 mt-1.5">
              Serials are reused across files, so a search returns candidates — read the holder and file number before ticking.
              Separate a list with commas, semicolons or new lines (not spaces).
            </p>
          </div>

          {{-- Advanced. Hidden by default: serial answers most of the work. --}}
          <div id="opm-advanced" class="hidden rounded-lg border border-slate-200 bg-slate-50/70 p-4 space-y-3">
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label for="opm-op-file" class="block text-[11px] font-semibold text-slate-600 uppercase tracking-wide mb-1">
                  Temp FileNo
                </label>
                <input type="text" id="opm-op-file" autocomplete="off" spellcheck="false"
                       placeholder="e.g. TEMP-144428"
                       class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500">
                {{-- Renamed to Temp FileNo because that is what an officer reads off the
                     permit, but the search still covers the confirmed MLS number too:
                     narrowing it would break every existing search that types one. --}}
                <p class="text-[10px] text-slate-400 mt-1">Also matches the confirmed MLS number.</p>
              </div>
              <div>
                <label for="opm-party" class="block text-[11px] font-semibold text-slate-600 uppercase tracking-wide mb-1">
                  Holder / grantee name
                </label>
                <input type="text" id="opm-party" autocomplete="off" spellcheck="false"
                       placeholder="Part of a name"
                       class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500">
                <p class="text-[10px] text-slate-400 mt-1">Narrows a search. Never use it alone if you can avoid it.</p>
              </div>
              <div>
                <label for="opm-prop-id" class="block text-[11px] font-semibold text-slate-600 uppercase tracking-wide mb-1">
                  Current Property ID
                </label>
                <input type="text" id="opm-prop-id" autocomplete="off" spellcheck="false"
                       placeholder="The id the permit carries now"
                       class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500">
              </div>
              <div>
                <label for="opm-plot-no" class="block text-[11px] font-semibold text-slate-600 uppercase tracking-wide mb-1">
                  Plot number
                </label>
                <input type="text" id="opm-plot-no" autocomplete="off" spellcheck="false"
                       placeholder="e.g. 3E"
                       class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500">
                {{-- Contains-match, not exact: the same plot is recorded as "3E",
                     "3 E" and "PLOT 3E" across the two source tables. --}}
                <p class="text-[10px] text-slate-400 mt-1">Partial match — "3" finds "3E".</p>
              </div>
            </div>

            <div class="flex flex-wrap gap-4 pt-1">
              <label class="inline-flex items-center gap-2 text-xs text-slate-600 cursor-pointer">
                <input type="checkbox" id="opm-hide-matched" checked
                       class="h-3.5 w-3.5 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500">
                Hide permits already on the target Property ID
              </label>
              <label class="inline-flex items-center gap-2 text-xs text-slate-600 cursor-pointer">
                <input type="checkbox" id="opm-unlinked-only"
                       class="h-3.5 w-3.5 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500">
                Only permits with no Transfer of Title yet
              </label>
            </div>
          </div>

          <div class="flex items-center gap-2">
            <button type="button" id="opm-op-search-btn"
                    class="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 rounded-lg transition shadow-sm">
              <i data-lucide="search" class="h-4 w-4"></i> Search OPs
            </button>
            <button type="button" id="opm-op-clear"
                    class="inline-flex items-center gap-2 px-3 py-2.5 text-sm font-medium text-slate-600 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg transition">
              Clear
            </button>

            {{-- The staging step. A file's permits rarely share one serial, so the officer
                 searches a serial, ticks what belongs to the file, adds it to the batch,
                 and searches the next serial. Without this the ticks would have to survive
                 every new search invisibly, and the officer would be matching a set they
                 could no longer see. --}}
            <button type="button" id="opm-add-btn" disabled
                    class="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-white bg-violet-600 hover:bg-violet-700 disabled:bg-slate-300 disabled:cursor-not-allowed rounded-lg transition shadow-sm">
              <i data-lucide="plus" class="h-4 w-4"></i>
              <span id="opm-add-label">Add to Batch</span>
            </button>

            <span id="opm-op-count" class="text-xs text-slate-500 ml-auto"></span>
          </div>

          <div id="opm-op-results" class="hidden"></div>
        </div>
      </section>
    </div>

    {{-- ============================ 3: Batch Match ============================ --}}
    <section class="mt-5 bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
      <header class="px-6 py-4 border-b border-slate-200 bg-gradient-to-r from-slate-50 to-white">
        <div class="flex items-center gap-3">
          <span class="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-800 text-white text-sm font-bold">3</span>
          <div>
            <h2 class="text-base font-semibold text-slate-900">Batch Match</h2>
            <p class="text-xs text-slate-500">Selected OP Property IDs → the confirmed file's Property ID.</p>
          </div>
          <button type="button" id="opm-staged-clear"
                  class="hidden ml-auto text-xs font-medium text-slate-500 hover:text-rose-600 transition">
            Remove all
          </button>
        </div>
      </header>

      <div class="p-6">
        {{-- The batch as it stands. Everything that will be written is listed here, so the
             officer is never matching a set they cannot see — including the permits added
             from a serial they searched several searches ago. --}}
        <div id="opm-staged" class="hidden mb-4"></div>

        <div id="opm-summary" class="text-sm text-slate-500 mb-4">
          Select a confirmed file on the left and at least one OP on the right.
        </div>

        <label class="inline-flex items-start gap-2 text-xs text-slate-600 cursor-pointer mb-4">
          <input type="checkbox" id="opm-move-companions" checked
                 class="mt-0.5 h-3.5 w-3.5 rounded border-slate-300 text-slate-800 focus:ring-slate-500">
          <span>
            <span class="font-medium text-slate-700">Move linked Transfer of Title rows with each permit</span><br>
            <span class="text-slate-400">
              A permit and the transfer written against it are one parcel. Leaving the transfer on the abandoned
              Property ID splits the file's history in two — untick this only if you know the transfer belongs elsewhere.
            </span>
          </span>
        </label>

        <div class="flex flex-wrap items-center gap-3">
          <button type="button" id="opm-batch-btn" disabled
                  class="inline-flex items-center gap-2 px-6 py-3 text-sm font-semibold text-white bg-slate-900 hover:bg-slate-800 disabled:bg-slate-300 disabled:cursor-not-allowed rounded-lg transition shadow-sm">
            <i data-lucide="git-merge" class="h-4 w-4"></i>
            <span id="opm-batch-label">Batch Match</span>
          </button>
          <span class="text-xs text-slate-400">This rewrites the Property ID on the selected records. It can be undone below.</span>
        </div>
      </div>
    </section>

    {{-- Recent batches, with Undo. A bulk parcel-id rewrite that cannot be taken back
         is not a safe thing to put in front of an officer. --}}
    <section class="mt-5 bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
      <header class="px-6 py-3.5 border-b border-slate-200 flex items-center justify-between">
        <h2 class="text-sm font-semibold text-slate-700 flex items-center gap-2">
          <i data-lucide="history" class="h-4 w-4 text-slate-400"></i> Recent matches
        </h2>
        <button type="button" id="opm-batches-refresh"
                class="text-xs font-medium text-slate-500 hover:text-slate-700 transition">Refresh</button>
      </header>
      <div id="opm-batches" class="p-4 text-sm text-slate-400">Loading…</div>
    </section>

  </div>
</div>

{{-- The shared file picker's markup. Without it GlobalFileNoModal.open() finds no
     #global-fileno-modal and bails, so the Select File Number button would do nothing. --}}
@include('components.global-fileno-modal')
@endsection

@push('scripts')
{{-- select2 is NOT loaded here. The picker component above carries its own copy (CSS
     and JS, inside an @once), and that script tag is parsed before this stack, so
     $.fn.select2 already exists by the time global-fileno-modal.js runs. Adding a
     second copy would re-define the plugin over the widgets the component just built.
     jQuery comes from layouts/app, above both. op-propid-match.js goes last: it calls
     GlobalFileNoModal.open(), and it checks the object is there before doing so. --}}
<script src="{{ asset('js/global-fileno-modal.js') }}"></script>
<script src="{{ asset('js/op-propid-match.js') }}?v={{ @filemtime(public_path('js/op-propid-match.js')) ?: time() }}"></script>
@endpush
