-- EDMS Schema Auto-Check Script (T-SQL for SQL Server)

-- Generated by EdmsSchemaChecker. Review and run manually.

SET NOCOUNT ON;

-- Ensure file_indexings has is_updated, batch_id, has_qc_issues and FK to batches
IF COL_LENGTH('file_indexings','is_updated') IS NULL
BEGIN
    ALTER TABLE file_indexings ADD is_updated BIT NOT NULL CONSTRAINT DF_file_indexings_is_updated DEFAULT(0);
END
IF COL_LENGTH('file_indexings','batch_id') IS NULL
BEGIN
    ALTER TABLE file_indexings ADD batch_id BIGINT NULL;
END
IF COL_LENGTH('file_indexings','has_qc_issues') IS NULL
BEGIN
    ALTER TABLE file_indexings ADD has_qc_issues BIT NOT NULL CONSTRAINT DF_file_indexings_has_qc_issues DEFAULT(0);
END
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_file_indexings_batches')
BEGIN
    IF COL_LENGTH('file_indexings','batch_id') IS NOT NULL AND EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = 'batches')
    BEGIN
        ALTER TABLE file_indexings
        ADD CONSTRAINT FK_file_indexings_batches FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE SET NULL;
    END
END

-- Ensure file_trackings has file_indexing_id and FK to file_indexings
IF COL_LENGTH('file_trackings','file_indexing_id') IS NULL
BEGIN
    ALTER TABLE file_trackings ADD file_indexing_id BIGINT NULL;
END
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_file_trackings_file_indexings')
BEGIN
    IF COL_LENGTH('file_trackings','file_indexing_id') IS NOT NULL AND EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = 'file_indexings')
    BEGIN
        ALTER TABLE file_trackings
        ADD CONSTRAINT FK_file_trackings_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;
    END
END

-- Ensure pagetypings table/columns exist
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'pagetypings')
BEGIN
    CREATE TABLE pagetypings (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        file_indexing_id BIGINT NOT NULL,
        scanning_id BIGINT NULL,
        page_number INT NOT NULL,
        page_type NVARCHAR(100) NOT NULL,
        page_subtype NVARCHAR(100) NULL,
        serial_number INT NOT NULL,
        page_code NVARCHAR(100) NULL,
        file_path NVARCHAR(255) NOT NULL,
        typed_by BIGINT NULL,
        source NVARCHAR(50) NOT NULL CONSTRAINT DF_pagetypings_source DEFAULT('initial'),
        qc_overridden BIT NOT NULL CONSTRAINT DF_pagetypings_qc_overridden DEFAULT(0),
        qc_override_note NVARCHAR(1000) NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_pagetypings_created_at DEFAULT (GETDATE()),
        updated_at DATETIME2 NOT NULL CONSTRAINT DF_pagetypings_updated_at DEFAULT (GETDATE()),
        deleted_at DATETIME2 NULL
    );
    CREATE INDEX IX_pagetypings_file_idx ON pagetypings(file_indexing_id);
    CREATE INDEX IX_pagetypings_scanning_id ON pagetypings(scanning_id);
    ALTER TABLE pagetypings ADD CONSTRAINT FK_pagetypings_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;
END
IF COL_LENGTH('pagetypings','source') IS NULL
BEGIN
    ALTER TABLE pagetypings ADD source NVARCHAR(50) NOT NULL CONSTRAINT DF_pagetypings_source DEFAULT('initial');
END
IF COL_LENGTH('pagetypings','qc_overridden') IS NULL
BEGIN
    ALTER TABLE pagetypings ADD qc_overridden BIT NOT NULL CONSTRAINT DF_pagetypings_qc_overridden DEFAULT(0);
END
IF COL_LENGTH('pagetypings','qc_override_note') IS NULL
BEGIN
    ALTER TABLE pagetypings ADD qc_override_note NVARCHAR(1000) NULL;
END
IF COL_LENGTH('pagetypings','deleted_at') IS NULL
BEGIN
    ALTER TABLE pagetypings ADD deleted_at DATETIME2 NULL;
END

-- Ensure property_records table/columns exist
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records')
BEGIN
    CREATE TABLE property_records (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        file_indexing_id BIGINT NOT NULL,
        instrument_type NVARCHAR(100) NOT NULL,
        reg_no NVARCHAR(100) NULL,
        reg_date DATE NULL,
        grantor NVARCHAR(255) NULL,
        grantee NVARCHAR(255) NULL,
        extras NVARCHAR(MAX) NULL,
        created_by BIGINT NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_property_records_created_at DEFAULT (GETDATE()),
        updated_at DATETIME2 NOT NULL CONSTRAINT DF_property_records_updated_at DEFAULT (GETDATE())
    );
    CREATE INDEX IX_property_records_file_idx ON property_records(file_indexing_id);
    ALTER TABLE property_records ADD CONSTRAINT FK_property_records_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','instrument_type') IS NULL
BEGIN
    ALTER TABLE property_records ADD instrument_type NVARCHAR(100) NOT NULL;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','reg_no') IS NULL
BEGIN
    ALTER TABLE property_records ADD reg_no NVARCHAR(100) NULL;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','reg_date') IS NULL
BEGIN
    ALTER TABLE property_records ADD reg_date DATE NULL;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','grantor') IS NULL
BEGIN
    ALTER TABLE property_records ADD grantor NVARCHAR(255) NULL;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','grantee') IS NULL
BEGIN
    ALTER TABLE property_records ADD grantee NVARCHAR(255) NULL;
END
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'property_records') AND COL_LENGTH('property_records','extras') IS NULL
BEGIN
    ALTER TABLE property_records ADD extras NVARCHAR(MAX) NULL;
END

-- Ensure batches table exists
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'batches')
BEGIN
    CREATE TABLE batches (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        name NVARCHAR(150) NOT NULL,
        size INT NOT NULL CONSTRAINT DF_batches_size DEFAULT(0),
        created_by BIGINT NULL,
        notes NVARCHAR(1000) NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_batches_created_at DEFAULT (GETDATE()),
        updated_at DATETIME2 NOT NULL CONSTRAINT DF_batches_updated_at DEFAULT (GETDATE())
    );
END

-- Ensure barcodes table exists
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'barcodes')
BEGIN
    CREATE TABLE barcodes (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        file_indexing_id BIGINT NOT NULL,
        barcode_value NVARCHAR(150) NOT NULL,
        qr_payload NVARCHAR(MAX) NULL,
        printed_at DATETIME2 NULL,
        created_at DATETIME2 NOT NULL CONSTRAINT DF_barcodes_created_at DEFAULT (GETDATE()),
        updated_at DATETIME2 NOT NULL CONSTRAINT DF_barcodes_updated_at DEFAULT (GETDATE())
    );
    CREATE UNIQUE INDEX UX_barcodes_barcode_value ON barcodes(barcode_value);
    CREATE INDEX IX_barcodes_file_idx ON barcodes(file_indexing_id);
    ALTER TABLE barcodes ADD CONSTRAINT FK_barcodes_file_indexings FOREIGN KEY (file_indexing_id) REFERENCES file_indexings(id) ON DELETE CASCADE;
END
