<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Adds `parent_prop_id` to `CofO_staging` for the KANGIS three-file linkage
 * model (guide-faithful "Option A").
 *
 * Why:
 *   Under the three-file model each file (Old KANGIS parent, Land, New KANGIS)
 *   carries its OWN prop_id, and children point up at the Old KANGIS parent via
 *   parent_prop_id. `pra` already has this column (OP->ToT lineage); CofO rows
 *   generated by the "Has Transaction" flow need the same so Legal Search's
 *   pra/CofO-level parent_prop_id expansion works for CofO instruments too.
 *
 * Column is nullable + indexed, matching the existing pra convention.
 */
return new class extends Migration
{
    private const CONNECTION = 'sqlsrv';
    private const TABLE = 'CofO_staging';

    public function up(): void
    {
        if (!Schema::connection(self::CONNECTION)->hasTable(self::TABLE)) {
            return;
        }

        Schema::connection(self::CONNECTION)->table(self::TABLE, function (Blueprint $table) {
            if (!Schema::connection(self::CONNECTION)->hasColumn(self::TABLE, 'parent_prop_id')) {
                $table->string('parent_prop_id', 50)->nullable();
            }
        });

        $this->createIndexIfMissing(
            'IX_CofO_staging_parent_prop_id',
            'CREATE INDEX [IX_CofO_staging_parent_prop_id] ON [' . self::TABLE . '] ([parent_prop_id])'
        );
    }

    public function down(): void
    {
        if (!Schema::connection(self::CONNECTION)->hasTable(self::TABLE)) {
            return;
        }

        $this->dropIndexIfExists('IX_CofO_staging_parent_prop_id');

        Schema::connection(self::CONNECTION)->table(self::TABLE, function (Blueprint $table) {
            if (Schema::connection(self::CONNECTION)->hasColumn(self::TABLE, 'parent_prop_id')) {
                $table->dropColumn('parent_prop_id');
            }
        });
    }

    private function createIndexIfMissing(string $indexName, string $createSql): void
    {
        $exists = DB::connection(self::CONNECTION)->selectOne(
            "SELECT 1 AS x FROM sys.indexes WHERE name = ? AND object_id = OBJECT_ID(?)",
            [$indexName, self::TABLE]
        );

        if (!$exists) {
            DB::connection(self::CONNECTION)->statement($createSql);
        }
    }

    private function dropIndexIfExists(string $indexName): void
    {
        $exists = DB::connection(self::CONNECTION)->selectOne(
            "SELECT 1 AS x FROM sys.indexes WHERE name = ? AND object_id = OBJECT_ID(?)",
            [$indexName, self::TABLE]
        );

        if ($exists) {
            DB::connection(self::CONNECTION)->statement(
                'DROP INDEX [' . $indexName . '] ON [' . self::TABLE . ']'
            );
        }
    }
};
