@extends('layouts.app')

@section('page-title')
    {{ __('Letter') }}
@endsection

@push('css')
<style>
    [x-cloak] { display: none !important; }
</style>
@endpush

@section('content')
    <div class="flex-1 overflow-auto bg-slate-50/60">
        @include('admin.header', [
            'PageTitle' => 'Letter',
            'PageDescription' => 'Generate and manage applications for consent for Deed of Assignment, Gift, and Mortgage.'
        ])

        <div class="p-6 space-y-8 max-w-7xl mx-auto">
            <!-- Hero -->
            <div class="bg-white rounded-3xl border border-slate-100 shadow-sm p-6 lg:p-8 space-y-6">
                <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">
                    <div>
                        <h1 class="text-3xl md:text-4xl font-bold text-slate-900 mt-1">Letter</h1>
                    </div>
                    <div class="flex flex-wrap items-center gap-3">
                        <button type="button" id="open-generate-modal"
                            class="hidden inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-blue-600 text-white font-semibold shadow hover:bg-blue-700 transition">
                            <i data-lucide="plus-circle" class="h-5 w-5"></i>
                           Generate Letter
                        </button>
                    </div>
                </div>
            </div>

            <!-- Stats -->
            <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div class="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
                    <p class="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Generated</p>
                    <p class="text-3xl font-bold text-slate-900 mt-2">{{ count($applications) }}</p>
                </div>
                <div class="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
                    <p class="text-xs font-semibold text-blue-600 uppercase tracking-wider">Deed of Assignment</p>
                    <p class="text-3xl font-bold text-blue-700 mt-2">{{ $applications->where('consent_type', 'Assignment')->count() }}</p>
                </div>
                <div class="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
                    <p class="text-xs font-semibold text-emerald-600 uppercase tracking-wider">Deed of Gift</p>
                    <p class="text-3xl font-bold text-emerald-700 mt-2">{{ $applications->where('consent_type', 'Gift')->count() }}</p>
                </div>

                
                    
                <div class="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
                    <p class="text-xs font-semibold text-amber-600 uppercase tracking-wider">Deed of Mortgage</p>
                    <p class="text-3xl font-bold text-amber-700 mt-2">{{ $applications->where('consent_type', 'Mortgage')->count() }}</p>
                </div>
            </div>

            <!-- Data Table -->
            <div class="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
                <div class="overflow-x-auto text-sm">
                    <table class="w-full text-left border-collapse" id="consent-table">
                        <thead class="bg-slate-50 border-b border-slate-100">
                            <tr>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">S/N</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px] whitespace-nowrap">File Number</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Consent Type</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Party 1</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Party 2</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Party 3</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Party 4</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Generated By</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">App. Date</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Time Generated</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Date Generated</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px]">Prints</th>
                                <th class="px-6 py-4 font-semibold text-slate-700 uppercase tracking-wider text-[11px] text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-100">
                            @forelse($applications as $app)
                                <tr class="hover:bg-slate-50/50 transition duration-200">
                                    <td class="px-6 py-4 text-slate-600 font-bold italic">{{ $loop->iteration }}</td>
                                    <td class="px-6 py-4 text-slate-900 font-bold whitespace-nowrap">
                                        <button type="button" class="view-properties-btn flex items-center gap-2 hover:text-blue-600 transition outline-none" 
                                                data-main-file="{{ $app->file_number }}"
                                                data-main-desc="{{ $app->property_description }}"
                                                data-main-applicant="{{ $app->applicant_name }}"
                                                data-additional="{{ json_encode($app->additional_properties ?? []) }}">
                                            <span>{{ $app->file_number }}</span>
                                            @php
                                                $additionalCount = is_array($app->additional_properties) ? count($app->additional_properties) : 0;
                                            @endphp
                                            @if($additionalCount > 0)
                                                <span class="inline-flex items-center justify-center px-2 py-0.5 rounded-full bg-amber-50 text-amber-600 text-[10px] font-bold border border-amber-200">
                                                    +{{ $additionalCount }}
                                                </span>
                                            @endif
                                        </button>
                                    </td>
                                    <td class="px-6 py-4">
                                        @php
                                            $badgeClass = match($app->consent_type) {
                                                'Assignment' => 'bg-blue-50 text-blue-700 border-blue-100',
                                                'Gift' => 'bg-emerald-50 text-emerald-700 border-emerald-100',
                                                'Mortgage' => 'bg-amber-50 text-amber-700 border-amber-100',
                                                default => 'bg-slate-50 text-slate-700 border-slate-100'
                                            };
                                        @endphp
                                        <span class="px-2.5 py-1 rounded-full text-[11px] font-bold uppercase border {{ $badgeClass }}">
                                            {{ $app->consent_type }}
                                        </span>
                                    </td>
                                    @php
                                        $titles = collect([$app->applicant_name]);
                                        if (is_array($app->additional_properties)) {
                                            foreach ($app->additional_properties as $prop) {
                                                if (!empty($prop['applicant_name'])) $titles->push($prop['applicant_name']);
                                                elseif (!empty($prop['applicant'])) $titles->push($prop['applicant']);
                                            }
                                        }
                                        $titles = $titles->filter()->unique()->values();
                                        
                                        $party1Text = 'N/A';
                                        if ($titles->count() === 1) {
                                            $party1Text = $titles->first();
                                        } elseif ($titles->count() === 2) {
                                            $party1Text = $titles->first() . ' & ' . $titles->last();
                                        } elseif ($titles->count() > 2) {
                                            $last = $titles->pop();
                                            $party1Text = $titles->implode(', ') . ', & ' . $last;
                                        }
                                    @endphp
                                    <td class="px-6 py-4 text-slate-900 font-semibold uppercase">{{ $party1Text }}</td>
                                    <td class="px-6 py-4 text-slate-900 font-semibold">{{ $app->party_name }}</td>
                                    @php
                                        $extraApplicants = collect($app->additional_applicants ?? [])->pluck('name')->filter()->values();
                                        $extraParties = collect($app->additional_parties ?? [])->pluck('name')->filter()->values();
                                        $otherPartyNames = $extraApplicants->merge($extraParties)->values();
                                    @endphp
                                    <td class="px-6 py-4 text-slate-900 font-semibold">{{ $otherPartyNames->get(0, 'N/A') }}</td>
                                    <td class="px-6 py-4 text-slate-900 font-semibold">{{ $otherPartyNames->get(1, 'N/A') }}</td>
                                    <td class="px-6 py-4">
                                        <div class="flex items-center gap-2">
                                            <div class="w-7 h-7 rounded-lg bg-slate-100 flex items-center justify-center text-slate-500">
                                                <i data-lucide="user-check" class="h-3.5 w-3.5"></i>
                                            </div>
                                            <span class="text-slate-600 text-sm font-medium">{{ $app->created_by ?: ($app->user ? $app->user->first_name . ' ' . $app->user->last_name : 'System') }}</span>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 text-slate-600 font-medium whitespace-nowrap text-xs">
                                        {{ optional($app->application_dated)->format('M d, Y') ?: 'N/A' }}
                                    </td>
                                    <td class="px-6 py-4 text-slate-600 font-medium whitespace-nowrap text-xs">
                                        {{ $app->created_at->format('h:i A') }}
                                    </td>
                                    <td class="px-6 py-4 text-slate-600 font-medium whitespace-nowrap text-xs">
                                        {{ $app->created_at->format('M d, Y') }}
                                    </td>
                                    <td class="px-6 py-4">
                                        <div class="flex items-center gap-2">
                                            <span class="w-2 h-2 rounded-full {{ $app->print_count > 0 ? 'bg-emerald-500' : 'bg-slate-300' }}"></span>
                                            <span class="font-bold text-slate-700">{{ $app->print_count }}</span>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4">
                                        <div class="flex items-center justify-center">
                                            <div x-data="{ open: false }" class="relative inline-block text-left">
                                                <button type="button" @click="open = !open" @click.away="open = false"
                                                    class="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-xl transition duration-200">
                                                    <i data-lucide="more-horizontal" class="h-5 w-5"></i>
                                                </button>

                                                <div x-show="open" x-cloak
                                                    x-transition:enter="transition ease-out duration-100"
                                                    x-transition:enter-start="transform opacity-0 scale-95"
                                                    x-transition:enter-end="transform opacity-100 scale-100"
                                                    x-transition:leave="transition ease-in duration-75"
                                                    x-transition:leave-start="transform opacity-100 scale-100"
                                                    x-transition:leave-end="transform opacity-0 scale-95"
                                                    class="absolute right-0 z-50 {{ $loop->remaining < 2 ? 'bottom-full mb-2 origin-bottom-right' : 'mt-2 origin-top-right' }} w-52 rounded-2xl bg-white shadow-2xl ring-1 ring-black ring-opacity-5 focus:outline-none overflow-hidden border border-slate-100">
                                                    <div class="py-2">
                                                        <!-- Edit Action -->
                                                        <div class="px-4 py-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-50 mb-1">Actions</div>
                                                        
                                                        @if($app->print_count == 0)
                                                            <button type="button" 
                                                                class="edit-consent-btn flex items-center gap-3 w-full px-4 py-2.5 text-xs text-amber-600 hover:bg-amber-50 transition font-bold" 
                                                                @click="open = false"
                                                                data-id="{{ $app->id }}"
                                                                data-app="{{ json_encode($app) }}">
                                                                <i data-lucide="edit-3" class="h-4 w-4"></i>
                                                                <span>Edit Application</span>
                                                            </button>
                                                        @else
                                                            <div class="flex items-center gap-3 w-full px-4 py-2.5 text-xs text-slate-300 cursor-not-allowed font-bold" title="Cannot edit after printing">
                                                                <i data-lucide="lock" class="h-4 w-4"></i>
                                                                <span>Edit</span>
                                                            </div>
                                                        @endif
                                                        @if($app->print_count < 2)
                                                            <a href="{{ route('consent-applications.show', $app->id) }}" target="_blank"
                                                                class="flex items-center gap-3 px-4 py-2.5 text-xs text-blue-600 hover:bg-blue-50 transition font-bold"
                                                                @click="open = false">
                                                                <i data-lucide="printer" class="h-4 w-4"></i>
                                                                <span>Print</span>
                                                            </a>
                                                        @else
                                                            <div class="flex items-center gap-3 w-full px-4 py-2.5 text-xs text-slate-300 cursor-not-allowed font-bold" title="Cannot print again">
                                                                <i data-lucide="printer" class="h-4 w-4"></i>
                                                                <span>Print</span>
                                                            </div>
                                                        @endif
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="13" class="px-6 py-12 text-center text-slate-500 italic">
                                        No applications found. Click "Generate" to create your first one.
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @include('consent_applications.partials.modal')
    @include('components.global-fileno-modal')

    <!-- Properties Modal -->
    <div id="properties-modal" class="fixed inset-0 z-[60] hidden flex items-center justify-center p-4">
        <div class="fixed inset-0 bg-slate-900/40 backdrop-blur-sm transition-opacity properties-modal-overlay"></div>
        <div class="relative bg-white rounded-3xl shadow-2xl w-full max-w-xl max-h-[85vh] flex flex-col overflow-hidden border border-slate-100 transform transition-all scale-95 opacity-0 duration-200" id="properties-modal-content">
            <div class="px-6 py-5 border-b border-slate-100 flex items-center justify-between bg-white shrink-0">
                <div>
                    <h3 class="text-xl font-bold text-slate-900">Properties Involved</h3>
                    <p class="text-xs text-slate-500 mt-1 uppercase tracking-widest font-semibold">List of file numbers and property descriptions</p>
                </div>
                <button type="button" class="close-properties-modal text-slate-400 hover:text-slate-600 p-2 hover:bg-slate-50 rounded-xl transition">
                    <i data-lucide="x" class="h-6 w-6"></i>
                </button>
            </div>
            <div class="p-6 overflow-y-auto space-y-4" id="properties-modal-list">
                <!-- Populated via JS -->
            </div>
        </div>
    </div>

    @push('scripts')
    <script src="{{ asset('js/global-fileno-modal.js') }}"></script>
    <script src="{{ asset('js/consent_applications.js') }}"></script>
    <script>
        window.consentFormVariant = 'letter';
        window.consentLandUseTypes = @json(($landUseTypes ?? collect())->values());
        window.consentPurposes = @json(($purposes ?? collect())->values());
        document.addEventListener('DOMContentLoaded', () => {
            if (window.lucide) {
                window.lucide.createIcons();
            }
            // Initialize Global Modal if not already 
            if (window.GlobalFileNoModal) {
                window.GlobalFileNoModal.init();
            }

            // Properties Modal Logic
            const propertiesModal = document.getElementById('properties-modal');
            const propertiesModalContent = document.getElementById('properties-modal-content');
            const propertiesModalList = document.getElementById('properties-modal-list');
            const overlay = document.querySelector('.properties-modal-overlay');
            const closeBtns = document.querySelectorAll('.close-properties-modal');

            function closePropertiesModal() {
                propertiesModalContent.classList.remove('scale-100', 'opacity-100');
                propertiesModalContent.classList.add('scale-95', 'opacity-0');
                setTimeout(() => {
                    propertiesModal.classList.add('hidden');
                }, 200);
            }

            closeBtns.forEach(btn => btn.addEventListener('click', closePropertiesModal));
            if (overlay) overlay.addEventListener('click', closePropertiesModal);

            document.querySelectorAll('.view-properties-btn').forEach(btn => {
                btn.addEventListener('click', function(e) {
                    e.stopPropagation();
                    const mainFile = this.dataset.mainFile;
                    const mainDesc = this.dataset.mainDesc || 'No description available';
                    const mainApplicant = this.dataset.mainApplicant || 'N/A';
                    let additional = [];
                    try {
                        additional = JSON.parse(this.dataset.additional || '[]');
                    } catch(e) {}

                    let html = `
                        <div class="p-4 rounded-xl border border-indigo-100 bg-indigo-50/30 space-y-2">
                            <div class="flex items-center justify-between">
                                <span class="text-[10px] font-bold text-indigo-500 uppercase tracking-widest">Primary Property</span>
                                <span class="px-2 py-1 bg-white border border-indigo-100 rounded text-xs font-mono font-bold text-indigo-700">${mainFile}</span>
                            </div>
                            <div class="mt-2 text-sm">
                                <p class="font-bold text-slate-800 uppercase mb-1">${mainApplicant}</p>
                                <p class="font-medium text-slate-700">${mainDesc}</p>
                            </div>
                        </div>
                    `;

                    if (additional && additional.length > 0) {
                        additional.forEach((prop, index) => {
                            const propApplicant = prop.applicant_name || prop.applicant || 'N/A';
                            html += `
                                <div class="p-4 rounded-xl border border-slate-100 bg-slate-50 space-y-2">
                                    <div class="flex items-center justify-between">
                                        <span class="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Additional Property ${index + 1}</span>
                                        <span class="px-2 py-1 bg-white border border-slate-200 rounded text-xs font-mono font-bold text-slate-700">${prop.file_number}</span>
                                    </div>
                                    <div class="mt-2 text-sm">
                                        <p class="font-bold text-slate-800 uppercase mb-1">${propApplicant}</p>
                                        <p class="font-medium text-slate-700">${prop.description || 'No description available'}</p>
                                    </div>
                                </div>
                            `;
                        });
                    }

                    propertiesModalList.innerHTML = html;
                    
                    propertiesModal.classList.remove('hidden');
                    // trigger reflow
                    void propertiesModal.offsetWidth;
                    propertiesModalContent.classList.remove('scale-95', 'opacity-0');
                    propertiesModalContent.classList.add('scale-100', 'opacity-100');
                });
            });
        });
    </script>
    @endpush
@endsection
