<?php

namespace App\Http\Controllers;

use App\Services\ReportService;
use App\Services\ActivityLogService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;

/**
 * ActivityLogReportsController
 *
 * Handles generation and management of activity log reports
 */
class ActivityLogReportsController extends Controller
{
    private $reportService;
    private $activityService;

    public function __construct(ReportService $reportService, ActivityLogService $activityService)
    {
        $this->reportService = $reportService;
        $this->activityService = $activityService;
    }

    /**
     * Display reports management page
     */
    public function index()
    {
        // Check authorization
        if (!Auth::user()->can('view-analytics') && Auth::user()->type !== 'super admin') {
            return redirect('/')->with('error', 'Unauthorized');
        }

        // Prepare view data
        $scheduledReports = $this->getScheduledReports();
        $recentReports = $this->getRecentReports();

        return view('activity.reports', [
            'scheduledReports' => $scheduledReports,
            'recentReports' => $recentReports,
        ]);
    }

    /**
     * Generate a new report
     */
    public function generate(Request $request)
    {
        // Check authorization
        if (!Auth::user()->can('generate-reports') && Auth::user()->type !== 'super admin') {
            return back()->with('error', 'You do not have permission to generate reports');
        }

        try {
            // Validate input
            $validated = $request->validate([
                'date_from' => 'required|date',
                'date_to' => 'required|date|after:date_from',
                'format' => 'required|in:csv,pdf,excel',
                'status' => 'nullable|in:ACTIVE,IDLE,INACTIVE',
                'user_search' => 'nullable|string',
            ]);

            // Prepare filters
            $filters = [
                'date_from' => $validated['date_from'],
                'date_to' => $validated['date_to'],
            ];

            if (!empty($validated['status'])) {
                $filters['status'] = $validated['status'];
            }

            // Generate report
            $result = $this->reportService->generateReport(
                $validated['format'],
                $filters,
                ['include_charts' => true]
            );

            if (!$result['success']) {
                return back()->with('error', $result['message'] ?? 'Failed to generate report');
            }

            // Log report generation
            Log::info("Report generated by {$request->user()->name}", [
                'format' => $validated['format'],
                'filename' => $result['filename'],
                'filters' => $filters,
            ]);

            // Return download or show success
            if ($request->has('download')) {
                return response()->download(
                    $result['path'],
                    $result['filename'],
                    ['Content-Type' => $this->getMimeType($result['format'])]
                );
            }

            return back()->with('success', "Report generated successfully: {$result['filename']} ({$result['size']} bytes)");

        } catch (\Illuminate\Validation\ValidationException $e) {
            return back()->withErrors($e->errors())->withInput();
        } catch (\Exception $e) {
            Log::error("Error generating report: {$e->getMessage()}");
            return back()->with('error', $e->getMessage());
        }
    }

    /**
     * Download a generated report
     */
    public function download(string $reportId)
    {
        // Check authorization
        if (!Auth::user()->can('view-reports') && Auth::user()->type !== 'super admin') {
            return redirect('/')->with('error', 'Unauthorized');
        }

        try {
            // Get report file path (would need to be stored in DB)
            // For now, return error
            return response()->json([
                'success' => false,
                'message' => 'Report file not found',
            ], 404);

        } catch (\Exception $e) {
            Log::error("Error downloading report: {$e->getMessage()}");
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Delete a report
     */
    public function destroy(string $reportId)
    {
        // Check authorization
        if (!Auth::user()->can('delete-reports') && Auth::user()->type !== 'super admin') {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized',
            ], 403);
        }

        try {
            // Delete report file (would need to retrieve from DB)
            Log::info("Report deleted: {$reportId} by {$request->user()->name}");

            return response()->json([
                'success' => true,
                'message' => 'Report deleted successfully',
            ]);

        } catch (\Exception $e) {
            Log::error("Error deleting report: {$e->getMessage()}");
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Schedule recurring report
     */
    public function scheduleReport(Request $request)
    {
        // Check authorization
        if (!Auth::user()->can('schedule-reports') && Auth::user()->type !== 'super admin') {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized',
            ], 403);
        }

        try {
            // Validate input
            $validated = $request->validate([
                'frequency' => 'required|in:daily,weekly,biweekly,monthly',
                'format' => 'required|in:csv,pdf,excel',
                'recipients' => 'required|email',
                'date_from' => 'nullable|date',
                'date_to' => 'nullable|date',
            ]);

            // Schedule report
            $result = $this->reportService->scheduleReport([
                'user_id' => Auth::id(),
                'frequency' => $validated['frequency'],
                'format' => $validated['format'],
                'recipients' => $validated['recipients'],
                'date_range' => [
                    'from' => $validated['date_from'] ?? null,
                    'to' => $validated['date_to'] ?? null,
                ],
            ]);

            Log::info("Report scheduled by {$request->user()->name}", [
                'frequency' => $validated['frequency'],
                'format' => $validated['format'],
            ]);

            return response()->json($result);

        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation error',
                'errors' => $e->errors(),
            ], 422);
        } catch (\Exception $e) {
            Log::error("Error scheduling report: {$e->getMessage()}");
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Delete scheduled report
     */
    public function destroySchedule(string $scheduleId)
    {
        // Check authorization
        if (!Auth::user()->can('schedule-reports') && Auth::user()->type !== 'super admin') {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized',
            ], 403);
        }

        try {
            Log::info("Scheduled report deleted: {$scheduleId} by {$request->user()->name}");

            return response()->json([
                'success' => true,
                'message' => 'Scheduled report deleted',
            ]);

        } catch (\Exception $e) {
            Log::error("Error deleting scheduled report: {$e->getMessage()}");
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Get scheduled reports
     */
    private function getScheduledReports(): array
    {
        // Would query database for scheduled reports
        // For now, return empty array
        return [];
    }

    /**
     * Get recent reports
     */
    private function getRecentReports(): array
    {
        // Would query database for recent reports
        // For now, return empty array
        return [];
    }

    /**
     * Get MIME type for format
     */
    private function getMimeType(string $format): string
    {
        return match($format) {
            'pdf' => 'application/pdf',
            'excel' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            default => 'text/csv',
        };
    }
}
